// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "8fa7c0af-360e-4028-871d-494762ddacd3");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1687747024);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1687747019);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{38294f4f-c8b3-40f6-ace4-165703f40e58}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1687747007);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9c31f658-1012-4f33-a383-6eeecb563f95}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230619192801");
user_pref("browser.startup.homepage_override.mstone", "114.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1687747011);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1687747017979");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "114.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "851043b7006447389fddd9f89e24c058");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230619192801");
user_pref("extensions.lastAppVersion", "114.0.2");
user_pref("extensions.lastPlatformVersion", "114.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"21f536b2-4d1c-496a-8de2-daff9ff79138\",\"pictureinpicture@mozilla.org\":\"7656e84a-8a47-4a33-8142-f512a5461e3a\",\"screenshots@mozilla.org\":\"4aacba69-0e00-4c8f-8892-b80e1b3ed268\",\"webcompat-reporter@mozilla.org\":\"af899537-7f27-431a-a235-8bc5456d3370\",\"webcompat@mozilla.org\":\"6e61e43f-9410-493c-9de3-b3285c11dbe1\",\"default-theme@mozilla.org\":\"e3b7a4ab-7a58-4120-82b2-7ea53c4a0e2c\",\"addons-search-detection@mozilla.com\":\"dea39cf5-be23-4c95-a4a5-3f4409fb02ff\",\"google@search.mozilla.org\":\"6bb5e238-0d97-4226-ba7f-7b10f60fb8e1\",\"amazondotcom@search.mozilla.org\":\"9fde5253-10cb-44e8-9b4c-5bd23b053eb1\",\"wikipedia@search.mozilla.org\":\"31ccb4a4-3e4e-4f31-bdea-0d2b738364e2\",\"bing@search.mozilla.org\":\"f0432b62-941b-41dc-ba68-3b671ab923ab\",\"ddg@search.mozilla.org\":\"fcdcd1a7-bb67-4576-82a4-b755ea80c87b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.accessibilityCache", "{\"slug\":\"next-generation-accessibility-engine-powering-screen-readers\",\"branch\":{\"slug\":\"treatment-a\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"accessibilityCache\"},\"features\":null},\"active\":true,\"enrollmentId\":\"584b8059-a55b-4391-ac8f-7152e1605caa\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Next generation accessibility engine powering screen readers\",\"userFacingDescription\":\"Evaluating a major re-architecture of Firefox's accessibility engine to improve performance of screen readers and other assistive technologies.\",\"lastSeen\":\"2023-06-26T02:36:59.242Z\",\"featureIds\":[\"accessibilityCache\"],\"prefs\":[{\"name\":\"accessibility.cache.enabled\",\"branch\":\"user\",\"featureId\":\"accessibilityCache\",\"variable\":\"enabled\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.accessibilityCache.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "1e2006c6-20f3-4111-b897-2a7df06192de");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1687746990);
user_pref("toolkit.telemetry.cachedClientID", "1f1c6702-13e3-4355-9308-00a71b3cdf10");
user_pref("toolkit.telemetry.previousBuildID", "20230619192801");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
